/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/tcTno5XcV3U
 */
import Link from "next/link"

export function HomeNews() {
  return (
    <div className="bg-white">
      <header className="border-b">
        <nav className="flex justify-between p-4">
          <div className="flex space-x-4">
            <Link className="font-bold" href="#">
              U.S.
            </Link>
            <div className="relative">
              <Link className="font-bold" href="#">
                World
              </Link>
              <ChevronDownIcon className="absolute top-0 right-0 h-4 w-4" />
            </div>
            <Link className="font-bold" href="#">
              Business
            </Link>
            <Link className="font-bold" href="#">
              Arts
            </Link>
            <div className="relative">
              <Link className="font-bold" href="#">
                Lifestyle
              </Link>
              <ChevronDownIcon className="absolute top-0 right-0 h-4 w-4" />
            </div>
            <Link className="font-bold" href="#">
              Opinion
            </Link>
            <Link className="font-bold" href="#">
              Audio
            </Link>
            <Link className="font-bold" href="#">
              Games
            </Link>
            <Link className="font-bold" href="#">
              Cooking
            </Link>
            <div className="relative">
              <Link className="font-bold" href="#">
                Wirecutter
              </Link>
              <ChevronDownIcon className="absolute top-0 right-0 h-4 w-4" />
            </div>
            <div className="relative">
              <Link className="font-bold" href="#">
                The Athletic
              </Link>
              <ChevronDownIcon className="absolute top-0 right-0 h-4 w-4" />
            </div>
          </div>
          <div className="flex items-center space-x-4">
            <SearchIcon className="h-6 w-6" />
            <UserCircleIcon className="h-6 w-6" />
          </div>
        </nav>
      </header>
      <main className="grid grid-cols-3 gap-4 p-4">
        <div className="col-span-2 space-y-6">
          <article>
            <h2 className="text-2xl font-bold">On the Ballot in Iowa: Fear, Anxiety and Hopelessness</h2>
            <p className="mt-2">
              Ahead of Monday’s caucuses, voters are throwing around the prospect of World War III and civil unrest,
              anxious of divisions they fear are tearing the U.S. apart.
            </p>
            <span className="block mt-2 text-sm font-medium">7 MIN READ</span>
          </article>
          <article>
            <h2 className="text-xl font-bold">In Iowa, Nikki Haley Has the Attention of Democrats and Independents</h2>
            <p className="mt-2">
              Ms. Haley has attracted the interest of non-Republicans who say they will caucus for her, as rivals attack
              her for an insufficiently conservative message.
            </p>
            <span className="block mt-2 text-sm font-medium">6 MIN READ</span>
          </article>
          <article>
            <h2 className="text-xl font-bold">
              Hillsdale College quietly became involved in many political fights — including the 2020 election plot.
            </h2>
            <span className="block mt-2 text-sm font-medium">25 MIN READ</span>
          </article>
          <article>
            <h2 className="text-xl font-bold">
              Much of Houthis’ Offensive Capability Is Intact After U.S.-Led Airstrikes
            </h2>
            <p className="mt-2">
              The first detailed assessments of the strikes in Yemen reveal the serious challenge facing the Biden
              administration as it seeks to deter Houthi aggression.
            </p>
          </article>
        </div>
        <div className="space-y-4">
          <div className="relative">
            <img
              alt="Iowa City,"
              className="h-[300px] w-full"
              height="300"
              src="/placeholder.svg"
              style={{
                aspectRatio: "500/300",
                objectFit: "cover",
              }}
              width="500"
            />
            <p className="absolute bottom-0 left-0 p-4 text-white">
              Congresswoman Ashley Hinson, left, introduces Nikki Haley during a campaign event at the James Theater.
            </p>
          </div>
          <div className="space-y-2">
            <div className="flex justify-between">
              <CircleIcon className="h-2 w-2" />
              <CircleIcon className="h-2 w-2" />
              <CircleIcon className="h-2 w-2" />
            </div>
            <div className="flex justify-between">
              <ChevronLeftIcon className="h-6 w-6" />
              <ChevronRightIcon className="h-6 w-6" />
            </div>
          </div>
          <div className="border-t border-b py-2">
            <p className="text-sm">
              LIVE <span className="text-xs">17m ago</span>
            </p>
            <p className="text-sm">
              Republican candidates are battling two forces in Iowa: brutally cold temperatures and the threat of low
              voter turnout.
            </p>
            <Link className="text-sm" href="#">
              See more updates
            </Link>
          </div>
          <div className="grid grid-cols-2 gap-4">
            <div>
              <img
                alt="Chicago's Latest Attraction?"
                className="h-[150px] w-full"
                height="150"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "150/150",
                  objectFit: "cover",
                }}
                width="150"
              />
              <h3 className="mt-2 text-lg font-bold">Chicago’s Latest Attraction? A Rat-Shaped Hole.</h3>
              <p className="mt-1 text-sm">
                A decades-old hole in the sidewalk has drawn millions of views online and even inspired Chicagoans to
                make offerings. No one knows where it came from.
              </p>
              <span className="block mt-1 text-xs font-medium">3 MIN READ</span>
            </div>
            <div>
              <img
                alt="After discovering bedbugs"
                className="h-[150px] w-full"
                height="150"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "150/150",
                  objectFit: "cover",
                }}
                width="150"
              />
              <h3 className="mt-2 text-lg font-bold">
                After discovering bedbugs, a reader asks: How do I get out of my lease?
              </h3>
            </div>
            <div>
              <img
                alt="The Ethicist columnist"
                className="h-[150px] w-full"
                height="150"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "150/150",
                  objectFit: "cover",
                }}
                width="150"
              />
              <h3 className="mt-2 text-lg font-bold">
                The Ethicist columnist is asked if prenatal testing for down syndrome amounts to eugenics.
              </h3>
            </div>
            <div>
              <img
                alt="Testing for Dromomania"
                className="h-[150px] w-full"
                height="150"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "150/150",
                  objectFit: "cover",
                }}
                width="150"
              />
              <h3 className="mt-2 text-lg font-bold">Testing for Dromomania</h3>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}


function ChevronDownIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m6 9 6 6-6" />
    </svg>
  )
}


function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}


function UserCircleIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <circle cx="12" cy="10" r="3" />
      <path d="M7 20.662V19a2 2 0 1 2-2h6a2 2v1.662" />
    </svg>
  )
}


function CircleIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
    </svg>
  )
}


function ChevronLeftIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m15 18-6-6 6-6" />
    </svg>
  )
}


function ChevronRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m9 18 6-6-6-6" />
    </svg>
  )
}
